<a href="https://colab.research.google.com/github/Hyewon-Git/2021_HUFS_NLP/blob/main/%ED%98%9C%EC%9B%90_NLP_03_00_matrix_equation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# EVN

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

import tensorflow as tf

# 행렬연산

## 데이터

In [ ]:
hidden = np.random.randint(-9, 10, (5, 4)) / 10
hidden

array([[-0.3, -0.7,  0.3, -0.4],
       [ 0.6,  0.2,  0.3, -0.5],
       [-0.2,  0.2, -0.5,  0.5],
       [ 0. ,  0.2, -0.2, -0.5],
       [-0.5, -0.7, -0.7,  0.3]])

## element wise sum

In [ ]:
arg = np.random.randint(-9, 10, (5, 4)) / 10
arg, hidden + arg

In [ ]:
arg = np.random.randint(-9, 10, (1, 4)) / 10
arg, hidden + arg

(array([[ 0.3, -0.5,  0.1,  0.5]]), array([[ 0. , -1.2,  0.4,  0.1],
        [ 0.9, -0.3,  0.4,  0. ],
        [ 0.1, -0.3, -0.4,  1. ],
        [ 0.3, -0.3, -0.1,  0. ],
        [-0.2, -1.2, -0.6,  0.8]]))

In [ ]:
arg = np.random.randint(-9, 10, (5, 1)) / 10
arg, hidden + arg

(array([[-0.7],
        [-0.5],
        [ 0.9],
        [-0.5],
        [-0.5]]), array([[-1. , -1.4, -0.4, -1.1],
        [ 0.1, -0.3, -0.2, -1. ],
        [ 0.7,  1.1,  0.4,  1.4],
        [-0.5, -0.3, -0.7, -1. ],
        [-1. , -1.2, -1.2, -0.2]]))

In [ ]:
arg = np.random.randint(-9, 10, (1, 1)) / 10
arg, hidden + arg

In [ ]:
hidden + 1

array([[0.7, 0.3, 1.3, 0.6],
       [1.6, 1.2, 1.3, 0.5],
       [0.8, 1.2, 0.5, 1.5],
       [1. , 1.2, 0.8, 0.5],
       [0.5, 0.3, 0.3, 1.3]])

In [ ]:
1 + hidden

array([[0.7, 0.3, 1.3, 0.6],
       [1.6, 1.2, 1.3, 0.5],
       [0.8, 1.2, 0.5, 1.5],
       [1. , 1.2, 0.8, 0.5],
       [0.5, 0.3, 0.3, 1.3]])

## element wise multiplication

In [ ]:
arg = np.random.randint(-9, 10, (5, 4)) / 10
arg, hidden * arg

(array([[ 0.1, -0.8, -0.6,  0.8],
        [ 0.7, -0.8,  0.2, -0.8],
        [-0.3, -0.8,  0.6, -0.9],
        [ 0.8,  0.1, -0.3, -0.2],
        [-0.1,  0.2, -0.4, -0.6]]), array([[-0.03,  0.56, -0.18, -0.32],
        [ 0.42, -0.16,  0.06,  0.4 ],
        [ 0.06, -0.16, -0.3 , -0.45],
        [ 0.  ,  0.02,  0.06,  0.1 ],
        [ 0.05, -0.14,  0.28, -0.18]]))

In [ ]:
arg = np.random.randint(-9, 10, (1, 4)) / 10
arg, hidden * arg

(array([[ 0.6,  0.8, -0.8, -0.6]]), array([[-0.18, -0.56, -0.24,  0.24],
        [ 0.36,  0.16, -0.24,  0.3 ],
        [-0.12,  0.16,  0.4 , -0.3 ],
        [ 0.  ,  0.16,  0.16,  0.3 ],
        [-0.3 , -0.56,  0.56, -0.18]]))

In [ ]:
arg = np.random.randint(-9, 10, (5, 1)) / 10
arg, hidden * arg

(array([[ 0.5],
        [ 0.1],
        [-0.8],
        [ 0.8],
        [ 0.6]]), array([[-0.15, -0.35,  0.15, -0.2 ],
        [ 0.06,  0.02,  0.03, -0.05],
        [ 0.16, -0.16,  0.4 , -0.4 ],
        [ 0.  ,  0.16, -0.16, -0.4 ],
        [-0.3 , -0.42, -0.42,  0.18]]))

In [ ]:
arg = np.random.randint(-9, 10, (1, 1)) / 10
arg, hidden * arg

(array([[-0.4]]), array([[ 0.12,  0.28, -0.12,  0.16],
        [-0.24, -0.08, -0.12,  0.2 ],
        [ 0.08, -0.08,  0.2 , -0.2 ],
        [-0.  , -0.08,  0.08,  0.2 ],
        [ 0.2 ,  0.28,  0.28, -0.12]]))

In [ ]:
hidden * 2

array([[-0.6, -1.4,  0.6, -0.8],
       [ 1.2,  0.4,  0.6, -1. ],
       [-0.4,  0.4, -1. ,  1. ],
       [ 0. ,  0.4, -0.4, -1. ],
       [-1. , -1.4, -1.4,  0.6]])

In [ ]:
2 * hidden

array([[-0.6, -1.4,  0.6, -0.8],
       [ 1.2,  0.4,  0.6, -1. ],
       [-0.4,  0.4, -1. ,  1. ],
       [ 0. ,  0.4, -0.4, -1. ],
       [-1. , -1.4, -1.4,  0.6]])

## matrix multiplication

In [ ]:
arg = np.random.randint(-9, 10, (4, 5)) / 10
arg, np.matmul(hidden, arg)

(array([[-0.9,  0.2, -0.8, -0.5,  0.4],
        [ 0.5,  0.6, -0.5,  0.1, -0.3],
        [-0.7,  0.6,  0.3,  0.3, -0.1],
        [ 0.1, -0.6,  0.2,  0. ,  0.4]]),
 array([[-0.33, -0.06,  0.6 ,  0.17, -0.1 ],
        [-0.7 ,  0.72, -0.59, -0.19, -0.05],
        [ 0.68, -0.52,  0.01, -0.03,  0.11],
        [ 0.19,  0.3 , -0.26, -0.04, -0.24],
        [ 0.62, -1.12,  0.6 , -0.03,  0.2 ]]))

In [ ]:
val = np.zeros((hidden.shape[0], arg.shape[1]))
val

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
#Dot 연산에대하여
for row in range(hidden.shape[0]):
    row_v = hidden[row]
    for col in range(arg.shape[1]):
        col_v = arg[:, col]
        val[row][col] = np.dot(row_v, col_v)
val

array([[-0.33, -0.06,  0.6 ,  0.17, -0.1 ],
       [-0.7 ,  0.72, -0.59, -0.19, -0.05],
       [ 0.68, -0.52,  0.01, -0.03,  0.11],
       [ 0.19,  0.3 , -0.26, -0.04, -0.24],
       [ 0.62, -1.12,  0.6 , -0.03,  0.2 ]])